version: "1"
module_version: 5.1.8


tests:
  - name: No-op Test1
    project_root: examples/default
 - name: No-op Test2
    project_root: examples/default
 - name: No-op Test3
    project_root: examples/default
 - name: No-op Test4
    project_root: examples/default
 - name: No-op Test5
    project_root: examples/default

vendor:
  terraform:
    version: "1.0.6" # Specify the desired Terraform version
